version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo Hello
      - IMAGE=${TAG/previous/latest}
      - |
        #!/bin/bash
        export REGION="us-east-1"
        export TAG="latest"
        echo REGION is $REGION
        echo IMAGE is $IMAGE
  post_build:
    commands:
      - echo Entered the post_build phase...
