version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo Hello
      - |
        export REGION="us-east-1"
        export TAG="latest"
        export COMMIT_ID="${COMMIT_ID:-$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)}"
        export IMAGE="$(echo "$TAG" | sed 's/latest/previous/')"
        export ECR_ACCOUNT_ID="${$ECR_ACCOUNT_ID:-AWS_ACCOUNT_ID}"
        echo REGION is $REGION
        echo IMAGE is $IMAGE
        echo COMMIT_ID is $COMMIT_ID
        echo AWS_ACCOUNT_ID is $ECR_ACCOUNT_ID
  post_build:
    commands:
      - echo Entered the post_build phase...
